name: traffic_gnn
channels:
- conda-forge
- pytorch
dependencies:
- python=3.10
- pandas
- requests
- jupyter
- matplotlib
- seaborn
- pyarrow
- fastparquet
- pytorch=1.12
- torchvision
- torchaudio
- cudatoolkit=11.6
- pip
- pip:
     - torch-geometric
     - torch-scatter
     - torch-sparse
