name: traffic_gnn
channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - numpy
  - pandas
  - requests
  - jupyter
  - matplotlib
  - seaborn
  - pyarrow
  - fastparquet
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - pytorch-cuda=12.1
  - pip
  - pip:
      - torch-geometric
      - torch-scatter
      - torch-sparse
